server:
  port: 8090

management:
  context-path: /management

spring:
  application:
    name: products

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/